## Matrices in Python Telusko

In [13]:
from numpy import *

In [23]:
arr1 = array([
    [1, 2, 3, 6, 2, 9],
    [4, 5, 6, 7, 5, 3]
])

print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

(2, 6)
2
12


In [24]:
## 2D Array to 1D
arr2 = arr1
arr2 = arr2.flatten()
print(arr2.shape)


(12,)


In [25]:
arr3 = arr2.reshape(3,4)
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [28]:
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [34]:
# matrices with numpy
m = matrix('1 2 3 6 ; 4 5 6 7')
m

matrix([[1, 2, 3, 6],
        [4, 5, 6, 7]])

In [35]:
m2 = matrix('1 2 3 ; 4 5 6 ; 7 8 9')
m2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
print("~~~")
print(m2)
print('M2 shape:', m2.shape)
print('Min is:', m2.min())

~~~
[[1 2 3]
 [4 5 6]
 [7 8 9]]
M2 shape: (3, 3)
Min is: 1


In [47]:
# Multiplying two matrices
m1 = matrix('1 2 3 ; 6 4 5 ; 1 6 7')
m2 = matrix('1 2 3 ; 6 8 5 ; 2 6 7')

m3 = m1 + m2
print(m3)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]
