## My crack at the solution

In [89]:
from numpy import matrix, array

class Matrix: 
    def __init__(self,matrix_string):
        my_string = matrix_string.replace('\n', ';')
        self.matrix_string = ''.join(my_string)
        
    def matrix_arr(self):
        return matrix(self.matrix_string)
    
    def __str__(self):
        return self.matrix_string

    def row(self, index):
        pass
    
    def column(self, index):
        pass

In [88]:
mat = Matrix('12 23 54 \n 30 40 50 \n 60 70 80')
print(mat)
print(mat.matrix_arr())

12 23 54 ; 30 40 50 ; 60 70 80
[[12 23 54]
 [30 40 50]
 [60 70 80]]
