## Numpy in 2020 Crash Course

## 1. Numpy Introduction 

- Core library for scientific computing in Python
    - Data Science, Machine Learning, Deep Learning
    - scikit-learn, matplotlib, pandas ...
- High Performance multidimensional array -> FAST!
- Mathematical operations with arrrays
- A lot of code written in C -> py functions are wrappers around C classes.

## Numpy Use-cases

- Array/Matrix operations - Linear Algebra
- Dot product
- Matrix multiplications
- Linear systems
- Inverse, determinant
- Eigenvectors
- Random numbers
- Working with images represented as array
- ...  
![](numpy2020-1.png)  

## The Code  

In [138]:
## Numpy import for whole notebook
import numpy as np

## Utility functions
def spacer():
    print('~~~~~~~~~~~~~~~~~~')

In [139]:
## Simply print the version to check
print(np.__version__)

1.19.1


In [140]:
## First array of the lecture
a = np.array([1,2,3])
print(a.shape)

(3,)


In [141]:
## Print array's data type
print(a.dtype)

int64


In [142]:
## Print array's dimensions
print(a.ndim)

1


In [143]:
## return total number of elements
print(a.size)

3


In [144]:
## returns the size in bytes of each element
print(a.itemsize)

8


In [145]:
## Indexing a numpy array --> returns the first element
print(a[0])

1


In [146]:
## altering values in the array
a[0] = 10
print(a)

[10  2  3]


In [147]:
## Array multiplication
b = a * np.array([2,0,2])
print(a,'Times [2,0,2] is equal to',b)

[10  2  3] Times [2,0,2] is equal to [20  0  6]


In [148]:
## Python lists vs np arrays

l = [1,2,3]
a = np.array([1,2,3])

def compare(l,a):
    print('   List   | np.array()')
    print('---------------------')
    print('',l,'',a)
reset(l,a)
compare(l,a)

   List   | np.array()
---------------------
 [1, 2, 3]  [1 2 3]


In [149]:
#l.append(4)
#a.append(4) # Has no attribute 'append'

# This spits out a no attribute exception
# compare(l,a)

In [150]:
# Now for something completely different
l = [1,2,3]
a = np.array([1,2,3])

l = l + [4]
a = np.array([1,2,3])
a = a + np.array([4]) # brut casting?
compare(l,a)

   List   | np.array()
---------------------
 [1, 2, 3, 4]  [5 6 7]


In [151]:
l = [1,2,3]
a = np.array([1,2,3])

l = l * 2
a = a * 2
compare(l,a)

   List   | np.array()
---------------------
 [1, 2, 3, 1, 2, 3]  [2 4 6]


In [152]:
# np.array functions
l = [1,2,3]
a = np.array([1,2,3])

a = np.log(a) # sqrt, 
print(a)

[0.         0.69314718 1.09861229]


In [153]:
# Dot Product
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

# # Naiive Method
# dot = 0
# for i in range(len(l1)):
#     dot += l1[i] * l2[i]
# print(dot)

dot = np.dot(a1,a2)
print(dot)

32


In [154]:
## Practice
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

# # Simple Way
# sum1 = a1 * a2
# dot = np.sum(sum1)
# print(dot)

# # More Pythonic way
# dot = (a1 * a2).sum()
# print(dot)

# Decorator function (CARNAGE MODE)
dot = a1 @ a2
print(dot)

32


In [155]:
## Numpy Speed Test
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a,b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start

print('list calculation', t1)
print('np.dot', t2)
print('ratio', t1/t2)

list calculation 0.3901469519996681
np.dot 0.001832060999731766
ratio 212.95521931681856


## ND Arrays (Multidimensional Arrays)

In [156]:
a = np.array([[1,2],[3,4]])
print('np.array:\n',a)
spacer()
print('a.shape :\n',a.shape)
spacer()
# print('a[0][0] =', a[0][0])
print('a[0][0] :\n',a[0][0])
spacer()
print('All rows in column 0',a[:,0])
print('All columns in row 0',a[0,:])

np.array:
 [[1 2]
 [3 4]]
~~~~~~~~~~~~~~~~~~
a.shape :
 (2, 2)
~~~~~~~~~~~~~~~~~~
a[0][0] :
 1
~~~~~~~~~~~~~~~~~~
All rows in column 0 [1 3]
All columns in row 0 [1 2]


In [157]:
## Get inverse of a
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [158]:
## Get the determinant
print(np.linalg.det(a))

-2.0000000000000004


In [159]:
## Return the diagonal matrix
c = np.diag(a)

print(a)
print(np.diag(c))


[[1 2]
 [3 4]]
[[1 0]
 [0 4]]


In [160]:
## Slicing
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
spacer()
b = a[0,:]
print(b)

[[1 2 3 4]
 [5 6 7 8]]
~~~~~~~~~~~~~~~~~~
[1 2 3 4]


#### Link: https://www.youtube.com/watch?v=9JUAPgtkKpI

#### Left off at 24:17
